### ISSUE TITLE
Error closing available upgrade dialog box

### ISSUE THREAD

**Issue by rumpled** [resin-io/etcher#1403]
- **Etcher version: 1.0.0-beta.18**
- **Operating system and architecture: OSX 10.12.14 MacBook Pro (Retina, 15-inch, Early 2013)**
- **Do you see any meaningful error information on DevTools? **
![image](https://cloud.githubusercontent.com/assets/563582/25916719/aeddf1de-3593-11e7-9ffc-19037824a22d.png)
```
TypeError: Cannot read property 'description' of undefined
    at reportException (/Applications/Etcher.app/Contents/Resources/app.asar/lib/gui/modules/error.js:44:51)
    at processQueue (/Applications/Etcher.app/Contents/Resources/app.asar/node_modules/angular/angular.js:16170:28)
    at /Applications/Etcher.app/Contents/Resources/app.asar/node_modules/angular/angular.js:16186:27
    at Scope.$eval (/Applications/Etcher.app/Contents/Resources/app.asar/node_modules/angular/angular.js:17444:28)
    at Scope.$digest (/Applications/Etcher.app/Contents/Resources/app.asar/node_modules/angular/angular.js:17257:31)
    at Scope.$apply (/Applications/Etcher.app/Contents/Resources/app.asar/node_modules/angular/angular.js:17552:24)
    at HTMLButtonElement.<anonymous> (/Applications/Etcher.app/Contents/Resources/app.asar/node_modules/angular/angular.js:25627:23)
    at defaultHandlerWrapper (/Applications/Etcher.app/Contents/Resources/app.asar/node_modules/angular/angular.js:3488:11)
    at HTMLButtonElement.eventHandler (/Applications/Etcher.app/Contents/Resources/app.asar/node_modules/angular/angular.js:3476:9)
    at HTMLButtonElement.d.util.hasFunction.f.(anonymous function) (file:///Applications/Etcher.app/Contents/Resources/app.asar/node_modules/trackjs/tracker.js:3:492) undefined
```

Steps to reproduce:
- Open Etcher 1.0.0-beta.18
- See alert window
- Click X in upper right corner of dialog
- Receive error

![image](https://cloud.githubusercontent.com/assets/563582/25916844/151876ea-3594-11e7-8d63-ad068277286d.png)

**Comment by jviotti** [comment]
Hi @rumpled ,

Thanks a lot for reporting this. This issue has already been fixed, so it will not happen on recent versions.

Sorry for the inconvenience!
