### ISSUE TITLE
Etcher v1.2.1 crashing on Windows 10

### ISSUE THREAD

**Issue by lurch** [resin-io/etcher#1967]
- **Etcher version:** 1.2.1
- **Operating system and architecture:** Windows 10 pro
- **Image flashed:** 2017-11-29-raspbian-stretch.img
- **Do you see any meaningful error information in the DevTools?**
```
|  ___| |     | |
| |__ | |_ ___| |__   ___ _ __
|  __|| __/ __| '_ \ / _ \ '__|
| |___| || (__| | | |  __/ |
\____/ \__\___|_| |_|\___|_|

Interested in joining the Etcher team?
Drop us a line at join+etcher@resin.io

Version = 1.2.1, Type = nsis
C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:55 Tue Jan 02 2018 11:11:33 GMT+0000 (GMT Standard Time) Application start ({"packageType":"nsis","version":"1.2.1"})
C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:55 Tue Jan 02 2018 11:11:33 GMT+0000 (GMT Standard Time) Checking for updates ({"currentVersion":"1.2.1","stable":true,"updateSemverRange":"<2.0.0","includeUnstableChannel":false})
C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:55 sdk start +580ms true
C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:55 Tue Jan 02 2018 11:11:35 GMT+0000 (GMT Standard Time) Update notification skipped ({"reason":"Latest version"})
C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:55 Tue Jan 02 2018 11:14:13 GMT+0000 (GMT Standard Time) Open image selector
C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:55 Tue Jan 02 2018 11:14:15 GMT+0000 (GMT Standard Time) Select image ({"path":"C:\\Users\\Jimmy\\OneDrive\\Downloads\\2017-11-29-raspbian-stretch\\2017-11-29-raspbian-stretch.img","extension":"img","size":{"original":4919918592,"final":{"estimation":false,"value":4919918592}},"hasMBR":true,"hasGPT":false,"partitions":[{"type":12,"id":null,"name":null,"firstLBA":8192,"lastLBA":93237,"extended":false},{"type":131,"id":null,"name":null,"firstLBA":94208,"lastLBA":9609216,"extended":false},{"type":0,"id":null,"name":null,"firstLBA":0,"lastLBA":0,"extended":false},{"type":0,"id":null,"name":null,"firstLBA":0,"lastLBA":0,"extended":false}],"logo":false,"bmap":false})
C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:55 sdk stop +3m true
C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:55 Tue Jan 02 2018 11:14:17 GMT+0000 (GMT Standard Time) Progress (undefined): 0% at 0 MB/s (eta undefineds)
C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:55 Tue Jan 02 2018 11:14:17 GMT+0000 (GMT Standard Time) Flash ({"image":"C:\\Users\\Jimmy\\OneDrive\\Downloads\\2017-11-29-raspbian-stretch\\2017-11-29-raspbian-stretch.img","drive":{"size":15931539456,"raw":"\\\\.\\PHYSICALDRIVE1","displayName":"D:","protected":false,"system":false,"adapter":"standard","device":"\\\\.\\PHYSICALDRIVE1","mountpoints":[{"path":"D:"}],"description":"SDHC Card"},"uuid":"c3568a23-5b9a-4b05-a5a7-c65492c8fdab","unmountOnSuccess":true,"validateWriteOnSuccess":true})
C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:55 openssl config failed: error:02001003:system library:fopen:No such process

C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:55 Tue Jan 02 2018 11:14:17 GMT+0000 (GMT Standard Time) Flash error ({"error":{"message":"Child process exited with code null, signal SIGTERM","stack":"Error: Child process exited with code null, signal SIGTERM\n    at ChildProcess.child.on (C:\\Users\\Jimmy\\AppData\\Local\\Programs\\etcher\\resources\\app.asar\\lib\\child-writer\\index.js:212:21)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:194:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)","code":null},"image":"C:\\Users\\Jimmy\\OneDrive\\Downloads\\2017-11-29-raspbian-stretch\\2017-11-29-raspbian-stretch.img","drive":{"size":15931539456,"raw":"\\\\.\\PHYSICALDRIVE1","displayName":"D:","protected":false,"system":false,"adapter":"standard","device":"\\\\.\\PHYSICALDRIVE1","mountpoints":[{"path":"D:"}],"description":"SDHC Card"},"uuid":"c3568a23-5b9a-4b05-a5a7-c65492c8fdab","unmountOnSuccess":true,"validateWriteOnSuccess":true})
C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:55 Tue Jan 02 2018 11:14:17 GMT+0000 (GMT Standard Time) Open modal ({"template":"./components/warning-modal/templates/warning-modal.tpl.html"})
C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:55 {"stack":"Error: Child process exited with code null, signal SIGTERM\n    at ChildProcess.child.on (C:\\Users\\Jimmy\\AppData\\Local\\Programs\\etcher\\resources\\app.asar\\lib\\child-writer\\index.js:212:21)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:194:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)","message":"Child process exited with code null, signal SIGTERM","code":null,"signal":"SIGTERM"}
console.(anonymous function) @ C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:55
logException @ C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\resin-corvus\src\resin…:228
exports.report @ C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\lib\gui\modules\exception-reporter.…:39
ImageWriterService.flash.then.catch @ C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\lib\gui\pages\main\controllers\flas…:103
processQueue @ C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\angular\angular.js:16843
(anonymous) @ C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\angular\angular.js:16887
$digest @ C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\angular\angular.js:17982
(anonymous) @ C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\angular\angular.js:18211
completeOutstandingRequest @ C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\angular\angular.js:6274
(anonymous) @ C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\angular\angular.js:6554
wrapped @ C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:416
C:\Users\Jimmy\AppData\Local\Programs\etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:55 sdk start +24s true
```

Creating this issue (so that the info doesn't get lost) on behalf of the user `JimmyWhite_UK_twitter` who reported this in our gitter chat.

> Hey all, first time user trying to flash an SD card with the lastest rasbian image - as soon as I click write, it crashes out with an error (sigterm) even when run as administrator.. Am I missing a pre-requisite?
....
No Joy sadly, same error with 1.2.0 - Ill wait for the next release

**Comment by jhermsmeier** [comment]
Closing this, as this has most likely been fixed in following versions, and this stack trace doesn't give us much to go on.
