### ISSUE TITLE
Can't clean drive

### ISSUE THREAD

**Issue by adman120** [resin-io/etcher#2453]
- **Etcher version:**  1.4.4
- **Operating system and architecture:** win 10 64bit
- **Image flashed:** https://dell.app.box.com/v/BootableR720/
- **Do you see any meaningful error information in the DevTools?** 
{"stack":"Error: Couldn't clean the drive, Command failed: diskpart /s C:\\Users\\Adam Tytel\\AppData\\Local\\Temp\\etcher-diskpart-e2c0cf8056aa\n (code 2147500037)\n    at retry.catch (C:\\Users\\Adam Tytel\\AppData\\Local\\Programs\\etcher\\resources\\app.asar\\lib\\cli\\diskpart.js:117:15)\n    at tryCatcher (C:\\Users\\Adam Tytel\\AppData\\Local\\Programs\\etcher\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Users\\Adam Tytel\\AppData\\Local\\Programs\\etcher\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:504:31)\n    at Promise._settlePromise (C:\\Users\\Adam Tytel\\AppData\\Local\\Programs\\etcher\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:561:18)\n    at Promise._settlePromise0 (C:\\Users\\Adam Tytel\\AppData\\Local\\Programs\\etcher\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:606:10)\n    at Promise._settlePromises (C:\\Users\\Adam Tytel\\AppData\\Local\\Programs\\etcher\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\promise.js:681:18)\n    at Async._drainQueue (C:\\Users\\Adam Tytel\\AppData\\Local\\Programs\\etcher\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:138:16)\n    at Async._drainQueues (C:\\Users\\Adam Tytel\\AppData\\Local\\Programs\\etcher\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:148:10)\n    at Immediate.Async.drainQueues (C:\\Users\\Adam Tytel\\AppData\\Local\\Programs\\etcher\\resources\\app.asar\\node_modules\\bluebird\\js\\release\\async.js:17:14)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)","message":"Couldn't clean the drive, Command failed: diskpart /s C:\\Users\\Adam Tytel\\AppData\\Local\\Temp\\etcher-diskpart-e2c0cf8056aa\n (code 2147500037)","name":"Error"}

**Comment by lurch** [comment]
Duplicate of #1793 ?
